spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=simple_api
        username: sa
        password: Password1
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        show-sql: true
        hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            ddl-auto: update
logging:
    level:
        org:
            springframework: ERROR
